### PR TITLE
CI: add macos-14

### PR DESCRIPTION
**Pull request by mgeier**
See also #384.

### CODE REVIEW

**Comment by HaHeho** [comment]
This is very strange what is going on with the `macos-14, Xcode_15.2` instance.

Looking through the logs I've noticed the following based on e.g. the `qt@5` package. `macos-13, Xcode_14.3` places installed homebrew packages into `/usr/local/opt/qt@5`, whereas they are placed in `/opt/homebrew/opt/qt@5/` on `macos-14, Xcode_15.2`.

`/usr/local/` does not seem to exist on the latter, which is the reason for the Intersense lib install as well as the fix to find `qt@5` during `./configure` to fail on `macos-14, Xcode_15.2`.

**Comment by HaHeho** [comment]
`macos-14, Xcode_15.2` ends up being Apple ARM (see https://github.com/SoundScapeRenderer/ssr/actions/runs/8410773165/job/23029617211?pr=394#step:1:11), although Apple Intel is also available for this combination.

For some reason (I guess this is the future), Apple ARM seems to be the default configuration on `macos-14`. If this is the current state, then it will probably stay like this. Apple Intel should be available, but I don't know if `macos-14-large` is available to open-source and for free (right now or ever). See the [list of available runners](https://github.com/actions/runner-images/tree/main?tab=readme-ov-file#available-images).

To fix this, we have to adapt the build pipeline to handle the slightly different environment on Apple ARM, including the different default install path of homebrew packages. However, supporting and testing builds on Apple ARM has been on the wishlist for a while. Free runners are available now, so this seems the right time to do it. I believe to remember that we started to gather information on what changes to the build scripts may be required?!

**Comment by mgeier** [comment]
Without really expecting it to work, I tried `macos-14` for the homebrew bottle: https://github.com/SoundScapeRenderer/homebrew-ssr/pull/30

And it seems to have worked without warnings!

This is without Intersense but it should be with libmysofa.

**Comment by mgeier** [comment]
> The following line on my local systems, Apple x86, and Apple ARM solves the problem `brew link --overwrite qt@5`. I would hope that this could replace the above lines on all macOS builds.

But didn't we change that in the opposite direction in #381?

I tried using `brew --prefix` in 70602451d3e5deb1d4783b06b4604661a6b50eb2, wouldn't this be better?

**Comment by HaHeho** [comment]
> > The following line on my local systems, Apple x86, and Apple ARM solves the problem `brew link --overwrite qt@5`. I would hope that this could replace the above lines on all macOS builds.
> 
> But didn't we change that in the opposite direction in #381?
> 
> I tried using `brew --prefix` in [7060245](https://github.com/SoundScapeRenderer/ssr/commit/70602451d3e5deb1d4783b06b4604661a6b50eb2), wouldn't this be better?

Yes, you're right. I didn't remember, but the outlined advantages to other users, i.e. the force link does not need to be reverted after building, seems reasonable. Although, maybe the `brew` behavior also has changed since then. Seems fine to keep that solution, and the change to `brew --prefix` is good to be Apple Intel vs Apple ARM agnostic.

Btw, in my local build on Apple ARM, I'm stuck at the same point as the CI (`ecasound` not being found after modifying `CPPFLAGS` and `LDFLAGS` like you did).

**Pull request merged**
