### PR TITLE
src/*: Removing vim:fdm (foldmethod) settings from all source files.

### PR DESCRIPTION
**Pull request by dvzrv**
Removing restrictive vim foldmethod settings from all source files.

### CODE REVIEW

**Comment by mgeier** [comment]
Thanks! You are right, those shouldn't be in there.

For completeness, you could also remove them from the `apf/` files?

**Comment by dvzrv** [comment]
Sure thing!
btw: will apf be included as a git submodule in the future?

**Comment by dvzrv** [comment]
I sqashed the last commit and renamed the message.

**Comment by mgeier** [comment]
> will apf be included as a git submodule in the future?

I don't know, should it?

Initially, I decided for `git subtree` instead, because then I'm the only one who has to worry about it. If you are interested, have a look at [update_apf.txt](../blob/master/update_apf.txt).

Using `git submodule` can be quite confusing for beginner and intermediate level Git users. I know it took me quite a while to get used to it ...

**Comment by chohner** [comment]
I think the idea of `git submodule` is both pretty elegant and straightforward to understand & maintain. But you are correct, you do need to run two more commands when cloning initially. I'd still argue that it's worth it.

**Comment by dvzrv** [comment]
`git submodule` seems indeed to be the more elegant solution compared to `git subtree`.
So far I found submodules quite easy to work with and it's a very well documented feature, too. It would most likely make testing of udpated apf versions a bit easier.  

Ultimately as maintainer you'll be responsible for the "current version" though.

**Comment by mgeier** [comment]
Regarding `submodule` vs. `subtree`:

I think it really depends on how the repository is being used. And this might change over time.

If the APF were a separately developed project with actual users and actual PRs created for it, it would probably make more sense to make it a `submodule`.

However, since it is currently mainly developed from inside of the SSR repo and the flow of information is mainly from SSR to APF, I think `subtree` actually makes more sense.

I guess there is one use case that is crucial:
If somebody wants to make a PR that changes things in both the SSR and the APF sources, this is only possible with `subtree`.
With `submodule`, one would have to make a separate PR for APF and then another one for SSR, changing the submodule to point to the APF PR. After the APF PR is merged, the SSR PR has to be changed to point the submodule back to APF `master` (unless it was fast-forward merged), and then the SSR PR can be merged.

Granted, there haven't been many PRs that manipulate both the APF and SSR code base, but I think it's nonetheless better if contributors don't have to worry about that.

What are the disadvantages of the current `git subtree` based approach?

> It would most likely make testing of udpated apf versions a bit easier.

Sure, but only if there was such a thing as "updated APF versions".
Currently, the APF doesn't change "on its own".

If at some point in the future this starts happening, we can switch to `git submodule`.

**Comment by dvzrv** [comment]
> Currently, the APF doesn't change "on its own".
> 
> If at some point in the future this starts happening, we can switch to git submodule.

Sounds reasonable!

Feel free to merge (so I can stop cherrypicking ;-) ).

**Comment by mgeier** [comment]
@JensAhrens Can you please merge whenever it's convenient for you?

**Comment by umlaeute** [comment]
just another note on `git submodules`: github doesn't include submodules in the auto-generated tarballs of tagged releases

so using submodules can make the automatic tarballs much less useful.

**Pull request merged**
