### PR TITLE
WIP demonstrate behavior creating ssr::Connection::Connection()

### PR DESCRIPTION
**Pull request by chris-hld**
WIP

Try with 
`python3 test_client.py`

See https://github.com/SoundScapeRenderer/ssr/issues/98.

### CODE REVIEW

**Comment by mgeier** [comment]
I still don't know what's causing the error, but I think I now have a somewhat better understanding of what is going on. I think this is an interesting place:

https://github.com/SoundScapeRenderer/ssr/blob/dd019edf0a6cfec823682a146b8998a46a218f5b/src/network/server.cpp#L59-L68

The time delay you introduced in the `Connection` class happens in the beginning of `start_accept()`.
If you would put the delay between `new_connection->start()` and `start_accept()`, I think it would be easier to understand what happens.

What happens if you remove the call to `start_accept()` here (and remove the time delay)?
This would mean that the network interface would only accept a single connection during its lifetime.
But it should still work with a single client.
I guess this doesn't cause the segmentation fault on Windows, right?

I guess (the preparation for) waiting for the next connection somehow causes the segfault.
I don't know why sleeping a short time seems to fix it ...

But the behavior when sleeping several seconds makes sense to me now: The line

    new_connection->start();

... gets the XML representation of the whole scene and immediately sends it to the new client.
After that, the line

    start_accept();

... sleeps a few seconds before it does anything, and after that it waits for a new connection (which doesn't happen in your current test case).
However, since the whole server runs in a single thread, sleeping while creating a new `Connection` object blocks the whole thread and therefore *all* existing connections. That's while the messages from the first connection only start to appear after the sleep time is over.

Does that make sense?

Can you please show the backtrace leading to the segfault?

**Comment by mgeier** [comment]
AFAIU, `handle_accept()` is called by ASIO when a client tries to connect. To handle this connection, it would be enough to call:

    new_connection->start();

The following call to `start_accept()` is to allow another connection to happen at a later time. And when a second connection happens, `start_accept()` is called again to allow a third connection and so on.

Did you try what happens if you remove the call to `start_accept()`?

I still don't see the race condition. What data is the race about?
I'm not sure but I think every call to `start_accept()` is called from the same thread, isn't it?

**Comment by chris-hld** [comment]
You are absolutely right. It should only be a single server thread. 
Unfortunately, it is very complicated for me to reproduce the error now. I don't have the old Windows machine on which it occurred on hand. Seemed like something that should have been handled by the ASIO library anyway.

Just to keep you in the loop, I upgraded my toolchain to GCC 8.1 and the latest ASIO library. Looks like it's fixed. I'll compile the binaries and make a new release on my side.

Regarding this PR, it's up to you. I will incorporate the mutex lock, because in my perspective it makes sense either way, especially since `handle_accept()` calls `start_accept()` again. And we don't know when and how this might happen.

**Comment by mgeier** [comment]
Thanks for the additional info. I agree that it sounded like a bug in ASIO, let's hope it never comes up again ...

I disagree about the mutex lock, though. Why would you use a lock anywhere in a single-threaded context?

> And we don't know when and how this might happen.

I think we should by now have a quite solid idea about that.
`handle_accept()` should be called by ASIO when a new client tries to connect. At this point, the previous call to `start_accept()` must already have finished, otherwise control wouldn't have been given back to ASIO to call `handle_accept()` in the first place. Therefore, `start_accept()` never runs twice at the same time.

AFAIU, in such a single-threaded asynchronous context, a "callback" function like `handle_accept()` call can be considered atomic. That's also the reason why calling `sleep()` should be avoided, because it blocks the whole asynchronous framework. If there *would be* another thread trying to do something, it would do it during the `sleep()`. But we already saw that's not the case, nothing happens during the `sleep()`.

Also, there is no reason why nothing else should happen between `Connection::create()` and `async_accept()` (which you seem to be trying to avoid with your lock). If anything, each of the calls should be locked separately. But since all this happens in only a single thread, this is not necessary.
If a lock *were* necessary here, it would also be necessary on *every single* call to any ASIO function, which clearly wouldn't make sense, right?

**Comment by mgeier** [comment]
I found some official documentation. I'm not 100% sure, but I think this is called to register the "callback" (or rather "handler"):

https://think-async.com/Asio/asio-1.10.6/doc/asio/reference/io_service/post.html

It says:

>  This function is used to ask the `io_service` to execute the given handler, but without allowing the `io_service` to call the handler from inside this function.
>
> The `io_service` guarantees that the handler will only be called in a thread in which the `run()`, `run_one()`, `poll()` or `poll_one()` member functions is currently being invoked.

**Comment by chris-hld** [comment]
Ah nice, looks like it is designed to be thread safe. OK, then it might have been a bug on the libasio side. Let's hope so.
I agree, the mutex lock is unnecessary in this case. I will remove it in the future.

**Pull request closed without merging**
