### PR TITLE
Toggle Solo state by key "s"

### PR DESCRIPTION
**Pull request by chris-hld**
The key "s" did not toggle the solo state, as you would expect it from all other multitrack audio softwares I'm familiar with. Very inconvenient, especially for demos, as you have to unselect all sources first and then hit "s" again.
The key "m" already shows the expected behaviour for mute (toggle) state.

- This PR improves the shortcut "s" and matches it to shortcut "m"

### CODE REVIEW

**Comment by chris-hld** [comment]
Is there any benefit in not renaming a nested iterator?

Also, I want to propose darkening the colour of muted sources. 
3b6531f755fc60502bdf911f8c243137db899a79
This makes it so much easier to recognize whether sources are in mute state.

**Comment by JensAhrens** [comment]
The darkening seems like a good idea. 

I have no opinion on the iterator...

**Comment by chris-hld** [comment]
I will split this PR into two.

**Comment by chris-hld** [comment]
https://github.com/SoundScapeRenderer/ssr/pull/89
https://github.com/SoundScapeRenderer/ssr/pull/90

**Pull request closed without merging**
