### PR TITLE
src/controller.h: Wrapping call to Subscriber::set_source_orientation…

### PR DESCRIPTION
**Pull request by dvzrv**
…() in a call to Scene::get_source_orientation() first, to make the former not segfault, if a non-existent Source is supplied.

### CODE REVIEW

**Comment by mgeier** [comment]
I guess the crash happens when dereferencing `*_scene.get_source_position(id)`, right?

What about checking the returned `unique_ptr` for non-NULL before calling `_publish()`?

That will have basically the same effect but it seems a bit less random ...

**Comment by dvzrv** [comment]
@mgeier Yes, you're right.
I just changed and tested this and it works. Eventually the amount of warning messages could be lowered somehow though (now two, in case of trying to position a non-existent source).

In any case, this is ready to be merged.

**Comment by mgeier** [comment]
Thanks.

This is perfectly fine as it is, but what do you think about avoiding a second call to the same function?

Something like this (untested!):

```c
if (auto src_pos = _scene.get_source_position(id))
{
  ...
  (... - *src_pos).orientation()
  ...
}
```

**Comment by dvzrv** [comment]
Good idea! Will try it out in a little bit and report back/push changes.

**Comment by mgeier** [comment]
I've added my suggested change, LGTM!

**Pull request merged**
