### PR TITLE
CI version upgrade

### PR DESCRIPTION
**Pull request by mgeier**
#297 failed, time for a CI upgrade.

### CODE REVIEW

**Comment by mgeier** [comment]
There seem to be some problems with the Intersense library on macOS, any ideas what's going wrong there?

**Comment by JensAhrens** [comment]
I'm not sure if it is really relevant to support InterSense nowadays. Should we simply remove it?

**Comment by mgeier** [comment]
I don't know if anybody uses the InterSense tracker ... maybe somebody does?

I don't think this is reason enough to completely remove support, because it still seems to work on Linux and older macOS versions. We could just remove it from the newer macOS CI.

I had a look at the `config.log` from the failing CI run, and this is the actual error message:

    ld: malformed universal file: slice content is not mach-o or a static library file '/usr/local/lib/libisense.dylib'

This seems to happen since Xcode 13.3.

**Comment by mgeier** [comment]
It looks like it works fine with Xcode 14 again, so I just removed the Xcode 13.4 check.

**Pull request merged**
